version: '3.8'
services:
  db:
    image: postgres:12-alpine
    ports:
      - 5436:5432
    environment:
      - POSTGRES_DB=particles
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    volumes:
        - particle_data:/var/lib/postgresql/data

volumes:
  particle_data:
